### PR TITLE
Permit multiple proposals

### PR DESCRIPTION
**Pull request by mildlyincompetent**
It is plausible for there to be multiple proposals for the dev team. We should enable this feature in the repo.

### CODE REVIEW

**Review by trickeydan — CHANGES_REQUESTED** [review]
You have not commented your code adequetely and it does not pass the unit tests.

**Comment by mildlyincompetent** [comment]
> You have not commented your code adequetely and it does not pass the unit tests.

**Comment by RealOrangeOne** [comment]
Whilst I agree with the premiss of this PR, #1 is incompatible with it, as it modifies the README directly, rather than creating a new file. 

We could either keep the PRs open and only merge the final one, which would solve this issue.

**Review by RealOrangeOne — APPROVED** [review]

**Comment by trickeydan** [comment]
I don't think this is currently necessary, as the current submission has been sent to Trustees.

**Pull request closed without merging**
